// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzlF1V00OycVgULGb9FOnIYU95XLFxcyI',
    appId: '1:891756904423:web:02e2130a85999487a28742',
    messagingSenderId: '891756904423',
    projectId: 'flutterfirestore-fa5ee',
    authDomain: 'flutterfirestore-fa5ee.firebaseapp.com',
    storageBucket: 'flutterfirestore-fa5ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ60pWtKiKYSzA-zsZrRZuq8OUTaQqEUA',
    appId: '1:891756904423:android:c372d667b0ad7b45a28742',
    messagingSenderId: '891756904423',
    projectId: 'flutterfirestore-fa5ee',
    storageBucket: 'flutterfirestore-fa5ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2N0_Yua_SLdR3MB3z3c3gJEucXvVMz30',
    appId: '1:891756904423:ios:844d5c1200a78fb5a28742',
    messagingSenderId: '891756904423',
    projectId: 'flutterfirestore-fa5ee',
    storageBucket: 'flutterfirestore-fa5ee.appspot.com',
    iosClientId:
        '891756904423-3ag4kqtg8bvtkled5ij9rqoov3pkq4d6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirestore',
  );
}
